### PR TITLE
Downgrade to 18.06.1 to support all RPi models

### LINKED ISSUE #271: headsup: docker arm6 broken
Hi,

while I'm building our xmas gifts... I just ran into some issue, they track it at docker here:
https://github.com/moby/moby/issues/38175

Solution: On ARMv6 one needs to downgrade docker to 18.06.1.
This is done by running ```# apt-get install docker-ce=18.06.1~ce~3-0~raspbian``` and gave me a working docker daemon.

----

What happens is they got a go issue and all parts of docker coredump :)
```
# systemctl start docker
Job for docker.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status docker.service" and "journalctl -xe" for details.
HypriotOS/armv6: root@rainbow in ~
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: inactive (dead) (Result: core-dump) since Sat 2018-12-15 02:45:39 UTC
     Docs: https://docs.docker.com
  Process: 2327 ExecStart=/usr/bin/dockerd -H unix:// (code=dumped, signal=SEGV)
 Main PID: 2327 (code=dumped, signal=SEGV)
      CPU: 462ms

Dec 15 02:45:39 rainbow systemd[1]: docker.service: Unit entered failed state.
Dec 15 02:45:39 rainbow systemd[1]: docker.service: Failed with result 'core-dum
Dec 15 02:45:39 rainbow systemd[1]: Stopped Docker Application Container Engine.
```

I'm not sure how I'll now adjust the image to include an older version, likely just run the image builder instead of just ```# flash```

In hindsight I find it really funny I expected I would just build those raspis using all known parts and it'd be all fine. Like, really? How did I think that! :-)

### PR DESCRIPTION
**Pull request by StefanScherer**
Downgrade from 18.09.0 to 18.06.1 to support all Raspberry Pi models.

Fixes #271

### CODE REVIEW

File: builder/test-integration/spec/hypriotos-image/docker_spec.rb [hunk 1]
```diff
@@ -75,13 +75,13 @@
...
 describe command('docker -v') do
-  its(:stdout) { should match /Docker version 18.09.0, build/ }
+  its(:stdout) { should match /Docker version 18.06.1, build/ }
   its(:exit_status) { should eq 0 }
 end
 
 describe command('docker version') do
-  its(:stdout) { should match /Client:. Version:           18.09.0. API version:       1.39/m }
-  its(:stdout) { should match /Server: Docker Engine - Community. Engine:.  Version:          18.09.0.  API version:      1.39/m }
+  its(:stdout) { should match /Client:. Version:           18.06.1. API version:       1.39/m }
```
Comment (StefanScherer) [inline builder/test-integration/spec/hypriotos-image/docker_spec.rb]: Probably we have to update the API version.

**Comment by StefanScherer** [comment]
ping @rossbachp FYI, we have to downgrade to 18.06.1 right now to support ARMv6 boards as well until https://github.com/moby/moby/issues/38175 is fixed 😬
